stages:
    - build
    - push

build_image:
    stage: build
    image: docker:20.10.17
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - >
            docker build
            --pull
            --cache-from $CI_REGISTRY_IMAGE:latest
            --label "org.varx.image.title=$CI_PROJECT_TITLE"
            --label "org.varx.image.url=$CI_PROJECT_URL"
            --label "org.varx.image.created=$CI_JOB_STARTED_AT"
            --label "org.varx.image.revision=$CI_COMMIT_SHA"
            --label "org.varx.image.version=$CI_COMMIT_REF_NAME"
            --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
            .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    tags:
        - build

push_image:
    stage: push
    image: docker:20.10.17
    tags:
        - push
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:latest
